import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { auth0 } from "../../lib/auth0";
import { AnalysisProvider } from "../../providers/AnalysisContext";
import { UserProvider, useUserCtx} from "../../providers/UserContext";
import Providers from "./Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Derm.AI",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth0.getSession();
  const initialUser = session
    ? { id: session.user.sub as string, email: session.user.email, name: session.user.name, picture: session.user.picture }
    : null;

    return (
        <html lang="en">
          <body>
            {/* <NavigationMenu>
              <NavigationMenuList>
                <NavigationMenuItem>
                  <NavigationMenuTrigger>Item One</NavigationMenuTrigger>
                  <NavigationMenuContent>
                    <NavigationMenuLink>Link</NavigationMenuLink>
                  </NavigationMenuContent>
                </NavigationMenuItem>
              </NavigationMenuList>
            </NavigationMenu> */}
            <UserProvider initialUser={initialUser}>
              <Providers />
              <AnalysisProvider>
                {children}
              </AnalysisProvider>
            </UserProvider>
            </body>
        </html>
    );
  }
